# Matugen generated colors for Spicetify

[Matugen]
text               = e1e3e2
subtext            = bfc8c7
main               = 111414
main-elevated      = 1d2020
main-transition    = 0c0f0e
highlight          = 191c1c
highlight-elevated = 323535
sidebar            = 0c0f0e
player             = 1d2020
card               = 272b2a
shadow             = 000000
selected-row       = e1e3e2
button             = 96d1cc
button-active      = b2eee8
button-disabled    = 96d1cc
tab-active         = 195854
notification       = fcb69b
notification-error = ffb4ab
misc               = 0c0f0e
play-button        = b4cbc8
play-button-active = d0e7e4
progress-fg        = 96d1cc
progress-bg        = 272b2a
heart              = ffb4ab
pagelink-active    = ffeae3
radio-btn-active   = ffeae3
