# Matugen generated colors for Kitty

# Core Colors
background            #1c1110
foreground            #f4dddc
selection_foreground  #ffb3af
selection_background  #68000d
cursor                #ffb3af
cursor_text_color     #1c1110
url_color             #73d9ba
# Kitty window border colors
active_border_color     #ffb3af
inactive_border_color   #584140

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #c84b4a
inactive_tab_foreground #dfbfbd
inactive_tab_background #584140

# Colors for marks (marked text in the terminal)
mark1_foreground #1c1110
mark1_background #73d9ba

# Regular Colors
color0  #342726
color1  #ffb4ab
color2  #ffb3af
color3  #73d9ba
color4  #ffffff
color5  #ffd7d4
color6  #ffb3af
color7  #f4dddc

# Bright Colors
color8  #443635
color9  #ffb4ab
color10 #ffb3af
color11 #73d9ba
color12 #ffffff
color13 #ffd7d4
color14 #ffb3af
color15 #f4dddc
