# Matugen generated colors for Kitty

# Core Colors
background            #111414
foreground            #e1e3e2
selection_foreground  #96d1cc
selection_background  #003734
cursor                #96d1cc
cursor_text_color     #111414
url_color             #fcb69b
# Kitty window border colors
active_border_color     #96d1cc
inactive_border_color   #3f4947

# Tab bar colors
active_tab_foreground   #bdfaf4
active_tab_background   #195854
inactive_tab_foreground #bfc8c7
inactive_tab_background #3f4947

# Colors for marks (marked text in the terminal)
mark1_foreground #111414
mark1_background #fcb69b

# Regular Colors
color0  #272b2a
color1  #ffb4ab
color2  #96d1cc
color3  #fcb69b
color4  #bdfaf4
color5  #d1e9e6
color6  #b4cbc8
color7  #e1e3e2

# Bright Colors
color8  #373a39
color9  #ffb4ab
color10 #96d1cc
color11 #fcb69b
color12 #bdfaf4
color13 #d1e9e6
color14 #b4cbc8
color15 #e1e3e2
