# Matugen generated colors for Kitty

# Core Colors
background            #0c1516
foreground            #dae4e5
selection_foreground  #fcba66
selection_background  #472a00
cursor                #fcba66
cursor_text_color     #0c1516
url_color             #8ed1de
# Kitty window border colors
active_border_color     #fcba66
inactive_border_color   #394a4c

# Tab bar colors
active_tab_foreground   #ffddb7
active_tab_background   #653e00
inactive_tab_foreground #b8cacc
inactive_tab_background #394a4c

# Colors for marks (marked text in the terminal)
mark1_foreground #0c1516
mark1_background #8ed1de

# Regular Colors
color0  #222c2d
color1  #ffb4ab                 
color2  #fcba66               
color3  #8ed1de              
color4  #ffddb7  
color5  #c5e7ff
color6  #a9cbe2             
color7  #dae4e5            

# Bright Colors
color8  #313b3c         
color9  #ffb4ab                  
color10 #fcba66                
color11 #8ed1de               
color12 #ffddb7   
color13 #c5e7ff 
color14 #a9cbe2              
color15 #dae4e5             